version: "2"
services:
  app:
    build: . 
    restart: always
    environment:
      - RUN_MIGRATIONS=true
    volumes:
      - public:/railsapp/public
    ports:
      - "3005:3000"

volumes:
  public:

